## 6/16/26 ndarray的特性
### 多维性


In [1]:
import numpy as np

生成并打印零维、一维、二维ndarray数组

In [ ]:
arr = np.array(5)
print(arr)
print("arr's number of dimensions:", arr.ndim)

5
arr's number of dimensions: 0


In [ ]:
arr = np.array([1, 2, 3])
print(arr)
print("arr's number of dimensions:", arr.ndim)

[1 2 3]
arr's number of dimensions: 1


In [ ]:
arr = np.array([ [1, 2, 3], [4, 5, 6] ])
print(arr)
print("arr's number of dimensions:", arr.ndim)

[[1 2 3]
 [4 5 6]]
arr's number of dimensions: 2


### 同质性

放入的数据类型若不同则会被强制转化为相同数据类型

In [ ]:
arr = np.array([1, "hello"])
print(arr)

['1' 'hello']


In [12]:
arr = np.array([1, 2.5])
print(arr)

[1.  2.5]
