## 6/16/26 ndarray的特性及属性
### 多维性


In [154]:
import numpy as np

生成并打印零维、一维、二维ndarray数组

In [155]:
arr = np.array(5)
print(arr)
print("arr's number of dimensions:", arr.ndim)

5
arr's number of dimensions: 0


In [156]:
arr = np.array([1, 2, 3])
print(arr)
print("arr's number of dimensions:", arr.ndim)

[1 2 3]
arr's number of dimensions: 1


In [157]:
arr = np.array([ [1, 2, 3], [4, 5, 6] ])
print(arr)
print("arr's number of dimensions:", arr.ndim)

[[1 2 3]
 [4 5 6]]
arr's number of dimensions: 2


### 同质性

放入的数据类型若不同则会被强制转化为相同数据类型

In [158]:
arr = np.array([1, "hello"])
print(arr)

['1' 'hello']


In [159]:
arr = np.array([1, 2.5])
print(arr)

[1.  2.5]


### 属性
shape     数组的形状, 行数和列数\
T         转置\
ndim      数组的维数\
itemsize  单个元素占用内存字节数\
dtype     元素类型\
nbytes    数组总内存占用量\
flags     内存储存方式是否连续

In [160]:
arr = np.array(1.0)
print(arr)
print("数组的形状几行几列: ", arr.shape)
print("元素的数据类型: ", arr.dtype)

arr = np.array([1, 2, 3])
print(arr)
print("数组的形状几行几列: ", arr.shape)

arr = np.array([ [1, 2, 3], [4, 5, 6] ])
print(arr)
print("数组的形状几行几列: ", arr.shape)
print("数组的转置: ", arr.T)


1.0
数组的形状几行几列:  ()
元素的数据类型:  float64
[1 2 3]
数组的形状几行几列:  (3,)
[[1 2 3]
 [4 5 6]]
数组的形状几行几列:  (2, 3)
数组的转置:  [[1 4]
 [2 5]
 [3 6]]


## 6/17/26 ndarry的创建

In [161]:
# 基础的创建方法就像前边那样
li = [[1, 2, 3], [4, 5, 6]]
arr = np.array(li, dtype = np.float64)    # 另加参数转换数据类型
print(arr, arr.dtype)


[[1. 2. 3.]
 [4. 5. 6.]] float64


In [162]:
# copy
arr1 = np.copy(arr)    # 拷贝后对arr1的修改不会影响arr原数组, 这说明内层嵌套不共享内存, 为深拷贝
arr1[0][0] = 100
print(arr, arr1, sep = "\n")

[[1. 2. 3.]
 [4. 5. 6.]]
[[100.   2.   3.]
 [  4.   5.   6.]]


In [163]:
# 预定义形状
# 全0 全1 未初始化 固定值
arr = np.zeros((2, 3)); print(arr, "这是全零数组 ")
arr = np.zeros((200, ), dtype = int); print(arr, "一行200个整型0 ")
arr = np.ones((5, 8), dtype = int); print(arr, "全一数组")
arr = np.empty((2, 3)); print(arr, "未初始化空数组执行更快")
arr = np.full((3, 4), 2026); print(arr, "填充其他内容设定")

[[0. 0. 0.]
 [0. 0. 0.]] 这是全零数组 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 一行200个整型0 
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]] 全一数组
[[0. 0. 0.]
 [0. 0. 0.]] 未初始化空数组执行更快
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]] 填充其他内容设定


In [164]:
arr1 = np.zeros_like(arr); print(arr1)    # 输出目标数组形状的数组
arr1 = np.full_like(arr, 666); print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[666 666 666 666]
 [666 666 666 666]
 [666 666 666 666]]


In [165]:
# 等差数列
arr = np.arange(1, 10, 1); print(arr)    # 与range()相同

# 等间隔数列, space形式都是包含末尾的, 下同
arr = np.linspace(0, 10, 5); print(arr)    # 设定首尾以及需要几个数
arr = np.arange(0, 11, 2.5); print(arr)    # arange这样写就可以达到同一效果, 注意不要写成"安排"

# 对数间隔数列
arr = np.logspace(0, 5, 6, base = 2); print(arr)    # 从0到5获取六个数记作pow, 依次输出base ** pow


[1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]
[ 1.  2.  4.  8. 16. 32.]


### 特殊矩阵

In [166]:
# 单位矩阵
arr = np.eye(3, dtype = int); print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [167]:
# 对角矩阵
arr = np.diag([1, 2, 3, 4]); print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [168]:
# 随机数组 (均匀分布)
# 生成0到1之间的随机浮点数
arr = np.random.rand(2, 3); print(arr)

# 指定范围 范围, 形状
arr = np.random.uniform(3, 6, (2, 3)); print(arr)

# 指定范围的随机整数
arr = np.random.randint(3, 10, (2, 3)); print(arr)

[[0.05671298 0.27265629 0.47766512]
 [0.81216873 0.47997717 0.3927848 ]]
[[5.50823629 4.01218848 4.94451562]
 [4.10472462 5.87146548 3.42105234]]
[[3 5 6]
 [3 4 6]]


In [169]:
# 随机数列 (标准正态分布, 均值0 标准差1)
arr = np.random.randn(3, 3); print(arr)

[[ 2.00815709  0.22988654  0.60489373]
 [ 1.62715982  1.59456053  0.23043417]
 [-0.06491034 -0.96898025  0.59124281]]


In [170]:
# 设定随机数种子
np.random.seed(20)
arr = np.random.randint(1, 10, (3, 3)); print(arr)

[[4 5 7]
 [8 3 1]
 [7 9 6]]


## 6/20/26 ndarray的数据类型
布尔类型 bool\
整数类型 int uint\
浮点数 float\
复数 complex

In [171]:
arr = np.array([1, 0, 1, 0], dtype = np.bool)
print(arr)

[ True False  True False]


### 索引与切片

In [172]:
# 一维数组的索引与切片, 语法与寻常切片一致
arr = np.random.randint(1, 100, 30)
print(arr)
print(arr[0: 6])
print(arr[(arr > 90) & (arr < 100)])    # 通过布尔条件筛选满足条件的元素, 可用逻辑运算符

[91 27 84 17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33 11
  7 76 19  4 78 18]
[91 27 84 17 63 17]
[91 99 95]


In [173]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (4, 4))
print(arr)
print(arr[1][3])    # 传统的分步索引
print(arr[1, 3])    # 元组索引, 效率更高, 仅可在numpy中使用, 在修改元素值时也采用此方法
print(arr[1: 3, 1: 3]) # 多行切片

[[44 17 19 80]
 [91 60 72 76]
 [30 46  7 64]
 [79 25 19 94]]
76
76
[[60 72]
 [46  7]]


### 运算方法

In [174]:
# 算数运算(对应位置计算)
a = np.array([2, 4, 6])
b = np.array([1, 2, 3])
print(a + b)    # 这里均为对应索引位置运算, 而原生列表的+是拼接
print(a // b)   # 不整除获取为浮点数
print(a + 3)    # 与标量运算时, 对其中每个元素均进行该运算

[3 6 9]
[2 2 2]
[5 7 9]


In [175]:
# 矩阵运算(正常的矩阵运算)
a = np.random.randint(1, 50, (3, 3))
e = np.eye(3, dtype = int)
print(f"{a}\n mul \n{e}\n is \n{a @ e}")

[[34 15 43]
 [31  4 19]
 [ 7 42 23]]
 mul 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
 is 
[[34 15 43]
 [31  4 19]
 [ 7 42 23]]


### 广播机制
! 不符合线性代数计算方法, 不建议使用\
无法扩展为同型不可广播\
以下的例子是将a向量拓展为:\
1 2 3\
1 2 3\
1 2 3\
将b向量拓展为:\
4 4 4\
5 5 5\
6 6 6\
再做矩阵加法\
视频弹幕又在吵了(‾◡◝)

In [176]:
a = np.array([1, 2, 3])    # 行向量
b = np.array([[4], [5], [6]])    # 列向量
print(a + b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


### numpy常用函数
基本数学函数

In [177]:
# 平方根
print(np.sqrt(9))
print(np.sqrt([4, 9, 16]))

arr = np.array([4, 9, 16])
print(np.sqrt(arr))

3.0
[2. 3. 4.]
[2. 3. 4.]


In [178]:
# 自然对数及e指数运算
print(np.exp(1))
print(np.log(2.718281828))

2.718281828459045
0.9999999998311266


In [179]:
# 三角函数
print(np.sin(np.pi))
print(np.cos(np.pi))

1.2246467991473532e-16
-1.0


In [180]:
# 绝对值
arr = np.array([1, -1, 3, -5])
print(np.abs(arr))

[1 1 3 5]


In [181]:
# 幂函数
arr = np.array([1, -1, 3, -5])
print(np.power(arr, 2))

[ 1  1  9 25]


In [182]:
# 银行家舍入法
# 减少累计误差 原生环境中round()函数也是这个方法
# 四舍六入五成双, 当一位小数为5时取最接近的偶数
arr = np.array([1.1, -1.6, 3.5, -5.4, 4.5])
print(np.round(arr))

[ 1. -2.  4. -5.  4.]


In [183]:
# 取整
arr = np.array([1.1, -1.6, 3.5, -5.4, 4.5])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. -1.  4. -5.  5.]
[ 1. -2.  3. -6.  4.]


In [184]:
# 检测缺失值
np.isnan([1, 2, 3, np.nan, 5])

array([False, False, False,  True, False])

统计函数

In [185]:
arr = np.random.randint(1, 20, 8)
print(arr)

[15  5 12  9  7 16 19 15]


In [186]:
# 求和
print(np.sum(arr))

# 平均数
print(np.mean(arr))

# 方差 标准差
print(np.var(arr))
print(np.std(arr))

# 最值
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

98
12.25
20.6875
4.548351349665063
19 6
5 1


In [187]:
# 中位数 偶数长度返回中间两数平均值
print(np.median(arr))

# 分位数 整体长度百分之多少的位置数值, 表明有百分之这么多的数小于输出值
print(np.percentile(arr, 50))    # 写作50的话就和中位数一个效果

# 累积和 也就是前缀和
print(np.cumsum(arr))
# 累积积 前缀积
print(np.cumprod(arr))

13.5
13.5
[15 20 32 41 48 64 83 98]
[       15        75       900      8100     56700    907200  17236800
 258552000]


比较函数

In [188]:
print(arr)
# 是否大于
print(np.greater(arr, 9))

# 是否小于
print(np.less(arr, 9))

# 是否等于
print(np.equal(arr, 9))
# 矩阵之间等于的比较需要保证形状相同

[15  5 12  9  7 16 19 15]
[ True False  True False False  True  True  True]
[False  True False False  True False False False]
[False False False  True False False False False]


逻辑运算

In [189]:
print(np.logical_and([1, 0], [0, 0]))
print(np.logical_not([1, 0]))
print(np.logical_or([1, 0], [0, 0]))
print(np.logical_xor([1, 0], [1, 0]))

# 检查是否至少有一个为True
print(np.any([0, 1, 0, 0, 0]))
# 检查是否全为True
print(np.all([0, 1, 0, 0, 0]))

[False False]
[False  True]
[ True False]
[False False]
True
False


自定义条件

In [190]:
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr > 3, arr, 0))

print(np.select([arr > 4, arr < 3], ['high', 'low'], default = '3 or 4'))

[0 0 0 4 5]
['low' 'low' '3 or 4' '3 or 4' 'high']


排序函数

In [191]:
np.random.seed(20)
arr = np.random.randint(1, 100, 10)
print(arr)
print(np.sort(arr))    # 不改变原始数组
print(np.argsort(arr)) # 打印原始索引

[91 16 96 29 91 10 21 76 23 72]
[10 16 21 23 29 72 76 91 91 96]
[5 1 6 8 3 9 7 0 4 2]


去重函数

In [192]:
print(arr)
print(np.unique(arr))

[91 16 96 29 91 10 21 76 23 72]
[10 16 21 23 29 72 76 91 96]


拼接与分割

In [193]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b)))

print(arr)
print(np.split(arr, [2, 4, 6, 8]))    # 下一数组开头位置, 一维数组切列, 多维数组切行

# 调整形状
print(arr)
print(np.reshape(arr, [2, 5]))

[1 2 3 4 5 6]
[91 16 96 29 91 10 21 76 23 72]
[array([91, 16], dtype=int32), array([96, 29], dtype=int32), array([91, 10], dtype=int32), array([21, 76], dtype=int32), array([23, 72], dtype=int32)]
[91 16 96 29 91 10 21 76 23 72]
[[91 16 96 29 91]
 [10 21 76 23 72]]


## 6/23/26 案例综合练习

1.温度数据分析\
某城市一周的最高气温为[28, 30, 29, 31, 32, 30, 29]\
计算平均气温最高气温与最低气温\
找出气温超过30的天数


In [194]:
import numpy as np
temps = np.array([28, 30, 29, 31, 32, 30, 29])

print(f"平均气温为: {np.mean(temps):.3f}")
print(f"最高气温为: {np.max(temps):d}")
print(f"最低气温为: {np.min(temps):d}")
print(f"超过30度的天数为: {len(temps[temps > 30])}")    # 布尔类型切片

li = np.where(temps > 30, 1, 0)
print(f"超过30度的天数为: {np.cumsum(li)[-1]}")    # 使用where判断加前缀和
print(f"超过30度的天数为: {np.count_nonzero(li)}") # 或者现成的命令

平均气温为: 29.857
最高气温为: 32
最低气温为: 28
超过30度的天数为: 2
超过30度的天数为: 2
超过30度的天数为: 2


2.学生成绩统计\
成绩为[85, 90, 78, 92, 88]\
计算成绩的平均分、中位数、标准差\
将成绩转化为百分制, 满分为10

In [195]:
import numpy as np
score = np.array([85, 90, 78, 92, 88])
print(f"平均分为: {np.mean(score)}")
print(f"中位数为: {np.median(score)}")
print(f"标准差为: {np.std(score):.3f}")
print(score / 100 * 10)

平均分为: 86.6
中位数为: 88.0
标准差为: 4.883
[8.5 9.  7.8 9.2 8.8]


3.矩阵运算
A = [[1, 2], [3, 4]]\
B = [[5, 6], [7, 8]]\
计算逐元素加法乘法\
计算矩阵乘法

In [196]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)
print(A * B)
print(A @ B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


4.随机数生成\
生成一个三行四列随机整数数列, 范围0-9\
计算每列中最大值和每行最小值\
将数组中所有奇数替换为-1

In [197]:
np.random.seed(0)
arr = np.random.randint(0, 10, (3, 4))
print(arr)
print(f"每列的最大值:{np.max(arr, axis = 0)}")    # 0为列, 1为行
print(f"每列的最大值:{np.min(arr, axis = 1)}")
print(np.where(arr % 2 == 1, -1, arr))    # where替换

arr[arr % 2 == 1] = -1; print(arr)    # 布尔索引替换也可行

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值:[7 9 7 6]
每列的最大值:[0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


5.数组变形\
创建一个1-12的一维数组, 并转换为3行4列的二维数组\
计算每行的和, 每列平均值\
将数组展开为1维数组

In [198]:
arr = np.arange(1, 13)
arr = np.reshape(arr, (3, 4))
print(arr)
print(f"每行的和为: {np.sum(arr, axis = 1)}")
print(f"每列的平均值为: {np.mean(arr, axis = 0)}")
arr = np.reshape(arr, (12))
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和为: [10 26 42]
每列的平均值为: [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


6.统计\
六个月的销售额为[120, 135, 110, 125, 130, 140]\
计算销售总和, 均值, 方差\
找出销售额最高和最低的月份

In [199]:
money = np.array([120, 135, 110, 125, 130, 140])
print(f"总和为: {np.sum(money)}")
print(f"平均值为: {np.mean(money):.3f}")
print(f"方差为: {np.var(money):.3f}")
print(f"最高的月份为: {np.argmax(money) + 1}")
print(f"最低的月份为: {np.argmin(money) + 1}")

总和为: 760
平均值为: 126.667
方差为: 97.222
最高的月份为: 6
最低的月份为: 3


7.数组拼接

In [200]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concat([a, b])    # 水平拼接
print(c)
print(c.reshape(2, 3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


8.唯一值与排序\
给定数组[2, 1, 2, 3, 1, 4, 3]\
找出数组唯一值并排序\
计算每个唯一值出现的次数

In [201]:
arr = np.array([2, 1, 2, 3, 1, 4, 3])
nex_arr, counts = np.unique(arr, return_counts = True)    # 该方法的若记不住就写for循环查数
print(nex_arr, counts)

[1 2 3 4] [2 2 2 1]


9.综合应用\
五天的销售额与成本如列表所写\
计算每天的利润\
计算利润的平均值与标准差\
找出利润最高的天数

In [202]:
total = np.array([20, 25, 22, 30, 28])
worth = np.array([15, 18, 16, 22, 20])

get = total - worth
print(get)
print(np.mean(get))
print(f"{np.std(get):.3f}")

print(len(get[get == np.max(get)]))    # 利用布尔索引输出最大值出现的次数

[5 7 6 8 8]
6.8
1.166
2
